service: create-product

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1

functions:
  hello:
    handler: createProduct.createProduct
    events:
      - http:
          path: admin/create
          method: post
          cors: true
