service: product-service

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1

functions:
  getProduct:
    handler: getProduct.getProduct
    events:
      - http:
          path: products
          method: get
  getProductById:
    handler: getProductById.getProductById
    events:
      - http:
          path: products/{productId}
          method: get
